/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("jlink.sample.java-conventions")
}

dependencies {
    api(project(":jlink.sample.service.base"))
}

description = "jlink-sample-modules-maven :: jlink.sample.service.a"
