/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.jdk.sample.jlink.test.java-conventions")
}

dependencies {
    api(project(":jlink-app"))
    api(project(":jlink-service-base"))
    api(project(":jlink-service-b"))
    api(project(":jlink-service-a"))
}

description = "jlink-sample-modules-maven :: jigsaw-jlink"
