/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.jdk.sample.jlink.test.java-conventions")
}
dependencies {
    api(project(":jlink-service-base"))
}

description = "jlink-sample-modules-maven :: jlink-service-b"
