/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "jlink-sample-modules-maven"
include(":jlink-service-b")
include(":jlink-service-base")
include(":jlink-app")
include(":jlink-service-a")
