/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "jlink-sample.modulessmaven"
include(":jlink.sample.service.b")
include(":jlink.sample.service.base")
include(":jlink.sample.sampleapp")
include(":jlink.sample.service.a")
